FROM maven:3.8.5-eclipse-temurin-17

# Install inotify-tools
RUN apt-get update && apt-get install -y inotify-tools

# Set the working directory
WORKDIR /app

# Copy the Maven build file
COPY pom.xml /app

COPY src/main/resources /app/src/main/resources

# Download dependencies (use caching if possible)
RUN mvn dependency:go-offline

# Copy the source code (will be overwritten by the volume)
COPY src /app/src

# Expose the application port
EXPOSE 8080
EXPOSE 35729

# Start the application using Spring Boot's Maven plugin
ENTRYPOINT ["/app/entrypoint.sh"]
