// app/layout.js

import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import ClientProvider from './ClientProvider'; // Import the ClientProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <nav className="p-6 bg-gray-800 text-white">
            <Link href="/" className="mr-4">Home</Link>
            <Link href="/about" className="mr-4">About</Link>
            <Link href="/contact" className="mr-4">Contact</Link>
            <Link href="/users" className="mr-4">Users</Link>
        </nav>
        <ClientProvider>
            {children}
        </ClientProvider>
        </body>
        </html>
    );
}
